mullemeck/build.py
mullemeck/settings.py
tests/test_build.py

Doesn't check that the checkout was successful as it was always failing, even though it managed to run the checkout

Fixed #108

---

mullemeck/__init__.py
mullemeck/processing.py

Fix task process not exiting on server shutdown

---

mullemeck/db.py
tests/test_db.py

Add tests for Build db model

---

poetry.lock
pyproject.toml

Move pdoc3 to dependencies from dev-deps

---

.travis.yml

Add deploy settings to travis config

---

mullemeck/db.py

Add docs for the db module

---

.travis.yml

Change Travis to deploy when master is updated

---

README.md

Add link to docs site in README

---

README.md

Add information about how to interact with server

---

mullemeck/processing.py

Add docs for the processing module

---

mullemeck/utils.py

Add documentation to the utils module

---

mullemeck/settings.py

Add documentation to the settings module

---

tests/test_build.py

Fixed #157

---

mullemeck/mail.py

Issue-121: fixed notify_build in mail.py

---

mullemeck/build.py
mullemeck/settings.py

Issue-169: fixed directory path for cloning, fixed spelling

---

README.md

Added my contributions to the readme file

Add Lars contributions to readme (Issue 64)

---

.travis.yml

Make Travis download get-poetry.py instead of pip

---

mullemeck/paginator.py
tests/test_frontend/test_paginator.py

Issue 167 Add documentation to paginator and its test file
Fixes: #167

Issue 167 Add documentation to paginator and its test file

---

mullemeck/__init__.py

Add documentation for the __init__ module

---

mullemeck/__main__.py

Add documentation to the __main__ module

---

.travis.yml

Issue-123-test: trying python version 3.7 in .travis.yml

---

poetry.lock
pyproject.toml

Bump python dependency to ^3.7

---

mullemeck/mail.py
mullemeck/routes.py

Forward committer_email to notify_build
